export class SelectedBillorCancel_DTO {
    AllowCancellation: boolean = true;
    BedChargeQuantityEditedDate: Date;
    BillStatus: string = '';
    BillingPackageId: number = 0;
    BillingTransactionItemId: number = 0;
    BillingType: string = '';
    CancelRemarks: string = '';
    CancelledBy: number = 0;
    CancelledOn: Date;
    CoPaymentCashAmount: number = 0;
    CoPaymentCreditAmount: number = 0;
    CounterDay: Date;
    CounterId: number = 0;
    CreatedBy: number = 0;
    CreatedOn: Date;
    DepartmenCode: string = '';
    DischargeStatementId: number = 0;
    DiscountAmount: number = 0;
    DiscountPercent: number = 0;
    DiscountPercentAgg: number;
    DiscountSchemeId: number = 0;
    IntegrationItemId: number = 0;
    IntegrationName: string = '';
    IsAutoBillingItem: Boolean = false;
    IsAutoCalculationStop: Boolean = false
    IsBedChargeQuantityEdited: false
    IsCashBillReturnSync: Boolean = false;
    IsCashBillSync: Boolean = false;
    IsCoPayment: Boolean = false;
    IsCreditBillReturnSync: Boolean = false;
    IsCreditBillSync: Boolean = false;
    IsInsurance: Boolean = false;
    IsProvisionalDischarge: Boolean = false;
    IsTransferredToACC: Boolean = false;
    ItemCode: string = '';
    ItemId: number = 0;
    ItemName: string = '';
    LabTypeName: string = '';
    ModifiedBy: number = 0;
    ModifiedOn: Date;
    NonTaxableAmount: number = 0;
    OrderStatus: string = '';
    PaidCounterId: number = 0;
    PaidDate: Date;
    PatientId: number = 0;
    PatientInsurancePackageId: number = 0;
    PatientVisitId: number = 0;
    PaymentReceivedBy: number = 0;
    PerformerId: number = 0;
    PerformerName: string = '';
    PrescriberId: number = 0;
    Price: number = 0;
    PriceCategory: string = '';
    PriceCategoryId: number = 0;
    ProcedureCode: string = '';
    ProvisionalFiscalYearId: number = 0;
    ProvisionalReceiptNo: number = 0;
    Quantity: number = 0;
    ReferredById: number = 0;
    Remarks: string = '';
    RequestingDeptId: number = 0;
    RequestingUserDept: string = '';
    RequestingUserName: string = '';
    RequisitionDate: Date;
    RequisitionId: number = 0;
    ReturnQuantity: number = 0;
    ReturnStatus: string = '';
    ReturnTax: number = 0;
    ServiceDepartmentId: number = 0;
    ServiceDepartmentName: string = '';
    ServiceItemId: number = 0;
    SubTotal: number = 0;
    Tax: number = 0;
    TaxPercent: number = 0;
    TaxableAmount: number = 0;
    TotalAmount: number = 0;
    VisitType: string = '';
}