import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { BillingSharedModule } from '../../app/billing/billing-shared.module';
import { ADT_DLService } from '../adt/shared/adt.dl.service';
import { AppointmentDLService } from '../appointments/shared/appointment.dl.service';
import { RegistrationSchemeSharedModule } from '../appointments/shared/registration-scheme/registration-scheme-shared.module';
import { VisitBLService } from '../appointments/shared/visit.bl.service';
import { VisitDLService } from '../appointments/shared/visit.dl.service';
import { BillingBLService } from '../billing/shared/billing.bl.service';
import { ClinicalNoteBLService } from '../clinical-new/shared/clinical.bl.service';
import { ClinicalNoteDLService } from '../clinical-new/shared/clinical.dl.service';
import { PatientSharedModule } from '../patients/patient-shared.module';
import { PatientsBLService } from '../patients/shared/patients.bl.service';
import { PHRMPatientConsumptionModule } from '../pharmacy/patient-consumption/phrm-patient-consumption.module';
import { PhrmOutpatientAddComponent } from '../pharmacy/sale/op-patient-add/phrm-op-patient-add.component';
import { PharmacyBLService } from '../pharmacy/shared/pharmacy.bl.service';
import { PharmacyDLService } from '../pharmacy/shared/pharmacy.dl.service';
import { PharmacyService } from '../pharmacy/shared/pharmacy.service';
import { SettingsSharedModule } from '../settings-new/settings-shared.module';
import { DanpheAutoCompleteModule } from '../shared/danphe-autocomplete/danphe-auto-complete.module';
import { SharedModule } from '../shared/shared.module';
import { ActivateDispensaryComponent } from './activate-dispensary/activate-dispensary.component';
import { ActivateCounterComponent } from './dispensary-main/activate-counter/activate-counter.component';
import { DispensaryMainComponent } from './dispensary-main/dispensary-main.component';
import { PatientDepositAddComponent } from './dispensary-main/patient-main/patient-deposit-add/patient-deposit-add.component';
import { PatientListComponent } from './dispensary-main/patient-main/patient-list/patient-list.component';
import { PatientMainComponent } from './dispensary-main/patient-main/patient-main.component';
import { PrescriptionListComponent } from './dispensary-main/prescription-main/prescription-list/prescription-list.component';
import { PrescriptionMainComponent } from './dispensary-main/prescription-main/prescription-main.component';
import { DispCashCollectionSummaryReportComponent } from './dispensary-main/reports-main/disp-cash-collection-summary-report/disp-cash-collection-summary-report.component';
import { DispDailySalesReportComponent } from './dispensary-main/reports-main/disp-daily-sales-report/disp-daily-sales-report.component';
import { DispDepositBalanceReportComponent } from './dispensary-main/reports-main/disp-deposit-balance-report/disp-deposit-balance-report.component';
import { DispensaryInvoiceBillingReportComponent } from './dispensary-main/reports-main/disp-invoice-billing-report/disp-invoice-billing-report.component.';
import { DispUserwiseCollectionReportComponent } from './dispensary-main/reports-main/disp-user-wise-collection-report/disp-userwise-collection-report.component';
import { DISPNarcoticsDailySalesReportComponent } from './dispensary-main/reports-main/narcotis-dailysales/disp-narcotis-daily-sales-report.component';
import { PaymentmodeWiseReportComponent } from './dispensary-main/reports-main/paymentmode-wise-report/paymentmode-wise-report.component';
import { ReportsMainComponent } from './dispensary-main/reports-main/reports-main.component';
import { SettlementSummaryReportComponent } from './dispensary-main/reports-main/settlement-summary-report/settlement-summary-report.component';
import { DISPStockSummaryReportComponent } from './dispensary-main/reports-main/stock-summary/disp-stock-summary-report.component';
import { DISPItemTxnSummaryComponent } from './dispensary-main/reports-main/stock-summary/item-txn-summary/disp-item-txn-summary-report.component';
import { PHRMDepositListComponent } from './dispensary-main/sales-main/deposit-receipt/phrm-deposit-list.component';
import { PHRMDepositReceiptComponent } from './dispensary-main/sales-main/deposit-receipt/phrm-deposit-receipt/phrm-deposit-receipt.component';
import { NewSalesComponent } from './dispensary-main/sales-main/new-sales/new-sales.component';
import { PHRMStockListComponent } from './dispensary-main/sales-main/new-sales/stock-list-pop-up/stock-list-pop-up.component';
import { PrintReceiptComponent } from './dispensary-main/sales-main/print-receipt/print-receipt.component';
import { ProvisionalBillsActionComponent } from './dispensary-main/sales-main/provisional-bills/provisioanl-bills-action/provisional-bills-action.component';
import { ProvisionalBillsFinalizeComponent } from './dispensary-main/sales-main/provisional-bills/provisional-bills-finalize/provisional-bills-finalize.component';
import { ProvisionalBillsUpdateComponent } from './dispensary-main/sales-main/provisional-bills/provisional-bills-update/provisional-bills-update.component';
import { ProvisionalBillsComponent } from './dispensary-main/sales-main/provisional-bills/provisional-bills.component';
import { ProvisionalReturnComponent } from './dispensary-main/sales-main/provisional-return/provisional-return.component';
import { SalesListComponent } from './dispensary-main/sales-main/sales-list/sales-list.component';
import { SalesMainComponent } from './dispensary-main/sales-main/sales-main.component';
import { SalesReturnListComponent } from './dispensary-main/sales-main/sales-return-list/sales-return-list.component';
import { ManualSalesReturnComponent } from './dispensary-main/sales-main/sales-return/manual-sales-return/manual-sales-return.component';
import { SalesReturnComponent } from './dispensary-main/sales-main/sales-return/sales-return.component';
import { PHRMDuplicatePrintSettlementListComponent } from './dispensary-main/sales-main/settlement/duplicate-print-settlement-list/duplicate-print-settlement-list.component';
import { PendingPHRMSettlementListComponent } from './dispensary-main/sales-main/settlement/pending-settlement-list/pending-settlement-list.component';
import { PHRMSettlementInvoiceDetail } from './dispensary-main/sales-main/settlement/phrm-settlement-invoice-detail.component';
import { SettlementReceiptComponent } from './dispensary-main/sales-main/settlement/settlement-receipt/settlement-receipt.component';
import { SettlementComponent } from './dispensary-main/sales-main/settlement/settlement.component';
import { DispensaryRequisitionEndpoint } from './dispensary-main/stock-main/requisition/dispensary-requisition-endpoint';
import { DispensaryRequisitionService } from './dispensary-main/stock-main/requisition/dispensary-requisition.service';
import { ReceiveDispatchedStockComponent } from './dispensary-main/stock-main/requisition/receive-dispatched-stock/receive-dispatched-stock.component';
import { RequisitionAddComponent } from './dispensary-main/stock-main/requisition/requisition-add/requisition-add.component';
import { RequisitionListComponent } from './dispensary-main/stock-main/requisition/requisition-list/requisition-list.component';
import { RequisitionViewComponent } from './dispensary-main/stock-main/requisition/requisition-view/requisition-view.component';
import { StockListComponent } from './dispensary-main/stock-main/stock-list/stock-list.component';
import { StockMainComponent } from './dispensary-main/stock-main/stock-main.component';
import { TransferCreateComponent } from './dispensary-main/stock-main/transfer-main/transfer-create/transfer-create.component';
import { TransferEndpointService } from './dispensary-main/stock-main/transfer-main/transfer-endpoint.service';
import { TransferListComponent } from './dispensary-main/stock-main/transfer-main/transfer-list/transfer-list.component';
import { TransferMainComponent } from './dispensary-main/stock-main/transfer-main/transfer-main.component';
import { TransferViewComponent } from './dispensary-main/stock-main/transfer-main/transfer-view/transfer-view.component';
import { TransferService } from './dispensary-main/stock-main/transfer-main/transfer.service';
import { DispensaryRoutingModule } from './dispensary-routing.module';
import { DispensaryGuardService } from './shared/dispensary-guard.service';
import { DispensaryProvisionalSalesReportComponent } from './dispensary-main/reports-main/disp-provisional-sales-report/disp-provisional-sales-report.component';

@NgModule({
  declarations: [DispensaryMainComponent, ActivateDispensaryComponent, ReportsMainComponent, ActivateCounterComponent, PatientMainComponent, PatientListComponent, PatientDepositAddComponent, PrescriptionMainComponent, PrescriptionListComponent, SalesMainComponent, SalesListComponent, NewSalesComponent, PhrmOutpatientAddComponent, SalesReturnComponent, SalesReturnListComponent, PrintReceiptComponent, ProvisionalBillsComponent, SettlementComponent, SettlementReceiptComponent, ProvisionalReturnComponent, StockMainComponent, StockListComponent, RequisitionListComponent, RequisitionAddComponent, RequisitionViewComponent, ReceiveDispatchedStockComponent, TransferMainComponent, TransferCreateComponent, TransferViewComponent, TransferListComponent, PHRMStockListComponent, DISPNarcoticsDailySalesReportComponent, DispUserwiseCollectionReportComponent, DispCashCollectionSummaryReportComponent, ManualSalesReturnComponent, DispDailySalesReportComponent, PHRMSettlementInvoiceDetail, PHRMDuplicatePrintSettlementListComponent, PendingPHRMSettlementListComponent, SettlementSummaryReportComponent, PaymentmodeWiseReportComponent, DISPStockSummaryReportComponent, DISPItemTxnSummaryComponent, PHRMDepositListComponent, PHRMDepositReceiptComponent, DispensaryInvoiceBillingReportComponent, DispDepositBalanceReportComponent, ProvisionalBillsUpdateComponent, ProvisionalBillsFinalizeComponent, ProvisionalBillsActionComponent, DispensaryProvisionalSalesReportComponent],
  providers: [DispensaryGuardService, PharmacyBLService, PharmacyDLService, PharmacyService, PatientsBLService, AppointmentDLService, VisitBLService, VisitDLService, ADT_DLService, BillingBLService, DispensaryRequisitionService, DispensaryRequisitionEndpoint, TransferService, TransferEndpointService, ClinicalNoteBLService, ClinicalNoteDLService],
  imports: [CommonModule, FormsModule, ReactiveFormsModule, DispensaryRoutingModule, SharedModule, SettingsSharedModule, DanpheAutoCompleteModule, PatientSharedModule, BillingSharedModule, PHRMPatientConsumptionModule, RegistrationSchemeSharedModule]
})
export class DispensaryModule { }
